name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install sdl
      run: git clone https://github.com/libsdl-org/SDL.git -b SDL2 & cd SDL & mkdir build & cd build & ../configure & make & sudo make install
    - name: make
      run: make
